# Generated by Django 5.2.8 on 2025-11-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uemail', models.CharField(max_length=122)),
                ('Upassword', models.CharField(max_length=122)),
            ],
        ),
    ]
