# Generated by Django 5.2.8 on 2025-11-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_login',
            old_name='Uemail',
            new_name='username',
        ),
    ]
