# Generated by Django 5.2.8 on 2025-11-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_uemail_user_login_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_login',
        ),
    ]
